/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class AudioCancion : TBase
{
  private string _nombreCancion;
  private byte[] _audio;

  public string NombreCancion
  {
    get
    {
      return _nombreCancion;
    }
    set
    {
      __isset.nombreCancion = true;
      this._nombreCancion = value;
    }
  }

  public byte[] Audio
  {
    get
    {
      return _audio;
    }
    set
    {
      __isset.audio = true;
      this._audio = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool nombreCancion;
    public bool audio;
  }

  public AudioCancion()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              NombreCancion = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Audio = await iprot.ReadBinaryAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("AudioCancion");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (NombreCancion != null && __isset.nombreCancion)
      {
        field.Name = "nombreCancion";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(NombreCancion, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Audio != null && __isset.audio)
      {
        field.Name = "audio";
        field.Type = TType.String;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteBinaryAsync(Audio, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as AudioCancion;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.nombreCancion == other.__isset.nombreCancion) && ((!__isset.nombreCancion) || (System.Object.Equals(NombreCancion, other.NombreCancion))))
      && ((__isset.audio == other.__isset.audio) && ((!__isset.audio) || (TCollections.Equals(Audio, other.Audio))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.nombreCancion)
        hashcode = (hashcode * 397) + NombreCancion.GetHashCode();
      if(__isset.audio)
        hashcode = (hashcode * 397) + Audio.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("AudioCancion(");
    bool __first = true;
    if (NombreCancion != null && __isset.nombreCancion)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("NombreCancion: ");
      sb.Append(NombreCancion);
    }
    if (Audio != null && __isset.audio)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Audio: ");
      sb.Append(Audio);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

