/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class AudioCancion : TBase
{
  private string _nombreCancion;
  private byte[] _audio;

  public string NombreCancion
  {
    get
    {
      return _nombreCancion;
    }
    set
    {
      __isset.nombreCancion = true;
      this._nombreCancion = value;
    }
  }

  public byte[] Audio
  {
    get
    {
      return _audio;
    }
    set
    {
      __isset.audio = true;
      this._audio = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool nombreCancion;
    public bool audio;
  }

  public AudioCancion() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            NombreCancion = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            Audio = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("AudioCancion");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (NombreCancion != null && __isset.nombreCancion) {
      field.Name = "nombreCancion";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(NombreCancion);
      oprot.WriteFieldEnd();
    }
    if (Audio != null && __isset.audio) {
      field.Name = "audio";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Audio);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("AudioCancion(");
    sb.Append("NombreCancion: ");
    sb.Append(NombreCancion);
    sb.Append(",Audio: ");
    sb.Append(Audio);
    sb.Append(")");
    return sb.ToString();
  }

}

