/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class ServicioReproduccion {
  public interface Iface {
    AudioCancion ObtenerCancion(string nombreArchivo);
    #if SILVERLIGHT
    IAsyncResult Begin_ObtenerCancion(AsyncCallback callback, object state, string nombreArchivo);
    AudioCancion End_ObtenerCancion(IAsyncResult asyncResult);
    #endif
    bool SubirAudio(AudioCancion audioCancion);
    #if SILVERLIGHT
    IAsyncResult Begin_SubirAudio(AsyncCallback callback, object state, AudioCancion audioCancion);
    bool End_SubirAudio(IAsyncResult asyncResult);
    #endif
  }

  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    public IAsyncResult Begin_ObtenerCancion(AsyncCallback callback, object state, string nombreArchivo)
    {
      return send_ObtenerCancion(callback, state, nombreArchivo);
    }

    public AudioCancion End_ObtenerCancion(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_ObtenerCancion();
    }

    #endif

    public AudioCancion ObtenerCancion(string nombreArchivo)
    {
      #if !SILVERLIGHT
      send_ObtenerCancion(nombreArchivo);
      return recv_ObtenerCancion();

      #else
      var asyncResult = Begin_ObtenerCancion(null, null, nombreArchivo);
      return End_ObtenerCancion(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_ObtenerCancion(AsyncCallback callback, object state, string nombreArchivo)
    #else
    public void send_ObtenerCancion(string nombreArchivo)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("ObtenerCancion", TMessageType.Call, seqid_));
      ObtenerCancion_args args = new ObtenerCancion_args();
      args.NombreArchivo = nombreArchivo;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public AudioCancion recv_ObtenerCancion()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      ObtenerCancion_result result = new ObtenerCancion_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "ObtenerCancion failed: unknown result");
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_SubirAudio(AsyncCallback callback, object state, AudioCancion audioCancion)
    {
      return send_SubirAudio(callback, state, audioCancion);
    }

    public bool End_SubirAudio(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_SubirAudio();
    }

    #endif

    public bool SubirAudio(AudioCancion audioCancion)
    {
      #if !SILVERLIGHT
      send_SubirAudio(audioCancion);
      return recv_SubirAudio();

      #else
      var asyncResult = Begin_SubirAudio(null, null, audioCancion);
      return End_SubirAudio(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_SubirAudio(AsyncCallback callback, object state, AudioCancion audioCancion)
    #else
    public void send_SubirAudio(AudioCancion audioCancion)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("SubirAudio", TMessageType.Call, seqid_));
      SubirAudio_args args = new SubirAudio_args();
      args.AudioCancion = audioCancion;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public bool recv_SubirAudio()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      SubirAudio_result result = new SubirAudio_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "SubirAudio failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["ObtenerCancion"] = ObtenerCancion_Process;
      processMap_["SubirAudio"] = SubirAudio_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void ObtenerCancion_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      ObtenerCancion_args args = new ObtenerCancion_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      ObtenerCancion_result result = new ObtenerCancion_result();
      result.Success = iface_.ObtenerCancion(args.NombreArchivo);
      oprot.WriteMessageBegin(new TMessage("ObtenerCancion", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void SubirAudio_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      SubirAudio_args args = new SubirAudio_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      SubirAudio_result result = new SubirAudio_result();
      result.Success = iface_.SubirAudio(args.AudioCancion);
      oprot.WriteMessageBegin(new TMessage("SubirAudio", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ObtenerCancion_args : TBase
  {
    private string _nombreArchivo;

    public string NombreArchivo
    {
      get
      {
        return _nombreArchivo;
      }
      set
      {
        __isset.nombreArchivo = true;
        this._nombreArchivo = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool nombreArchivo;
    }

    public ObtenerCancion_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              NombreArchivo = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ObtenerCancion_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (NombreArchivo != null && __isset.nombreArchivo) {
        field.Name = "nombreArchivo";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(NombreArchivo);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ObtenerCancion_args(");
      sb.Append("NombreArchivo: ");
      sb.Append(NombreArchivo);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ObtenerCancion_result : TBase
  {
    private AudioCancion _success;

    public AudioCancion Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public ObtenerCancion_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 0:
            if (field.Type == TType.Struct) {
              Success = new AudioCancion();
              Success.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ObtenerCancion_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.success) {
        if (Success != null) {
          field.Name = "Success";
          field.Type = TType.Struct;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          Success.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ObtenerCancion_result(");
      sb.Append("Success: ");
      sb.Append(Success== null ? "<null>" : Success.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SubirAudio_args : TBase
  {
    private AudioCancion _audioCancion;

    public AudioCancion AudioCancion
    {
      get
      {
        return _audioCancion;
      }
      set
      {
        __isset.audioCancion = true;
        this._audioCancion = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool audioCancion;
    }

    public SubirAudio_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              AudioCancion = new AudioCancion();
              AudioCancion.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SubirAudio_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AudioCancion != null && __isset.audioCancion) {
        field.Name = "audioCancion";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        AudioCancion.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SubirAudio_args(");
      sb.Append("AudioCancion: ");
      sb.Append(AudioCancion== null ? "<null>" : AudioCancion.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SubirAudio_result : TBase
  {
    private bool _success;

    public bool Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public SubirAudio_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 0:
            if (field.Type == TType.Bool) {
              Success = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SubirAudio_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.success) {
        field.Name = "Success";
        field.Type = TType.Bool;
        field.ID = 0;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Success);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SubirAudio_result(");
      sb.Append("Success: ");
      sb.Append(Success);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
